# Generated by Django 5.1.6 on 2025-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="姓名"
            ),
        ),
    ]
